input_cols_for_ordinal_encoder_r1:
  # 下のデータフレームのカラム名
  - curb_loc
  - steward
  - guards
  - sidewalk
  - user_type
  - problems
  - spc_common
  - spc_latin
  - nta
  - borocode
  - boro_ct
  - boroname
  - zip_city
  - cb_num
  - st_senate
  - st_assem
  - cncldist
  # parents のカラム名
  - spc_common_country
  - spc_common_main_type
  - spc_common_sub_type
  - spc_latin_genus
  - spc_latin_species
  - nta_char
  - nta_num
  - created_at__year
  - tree_age_bins10
  - tree_dbh_01

input_cols_for_ordinal_encoder_r2:
  # 下のデータフレームのカラム名
  - curb_loc
  - steward
  - guards
  - sidewalk
  - user_type
  # parents のカラム名
  - spc_common_country
  - spc_common_main_type
  - spc_common_sub_type
  - spc_latin_genus
  - spc_latin_species
  - nta_char
  - nta_num
  - created_at__year
  - tree_age_bins10
  - tree_dbh_01

group_keys_for_aggregation:
  # 下のデータフレームのカラム名
  - [curb_loc]
  - [steward]
  - [guards]
  - [sidewalk]
  - [user_type]
  - [problems]
  - [spc_common]
  - [spc_latin]
  - [nta]
  - [borocode]
  - [boro_ct]
  - [boroname]
  - [zip_city]
  - [cb_num]
  - [st_senate]
  - [st_assem]
  - [cncldist]
  # parents のカラム名
  - [spc_common_country]
  - [spc_common_main_type]
  - [spc_common_sub_type]
  - [spc_latin_genus]
  - [spc_latin_species]
  - [nta_char]
  - [nta_num]
  - [created_at__year]
  - [tree_age_bins10]
  - [tree_dbh_01]
  # boro_ct + α のカラム名
  - [boro_ct, curb_loc]
  - [boro_ct, steward]
  - [boro_ct, guards]
  - [boro_ct, sidewalk]
  - [boro_ct, user_type]
  - [boro_ct, spc_common_country]
  - [boro_ct, spc_latin_genus]
  - [boro_ct, created_at__year]
  - [boro_ct, tree_dbh_01]
  # spc_latin_genus + α のカラム名
  - [spc_latin_genus, curb_loc]
  - [spc_latin_genus, steward]
  - [spc_latin_genus, guards]
  - [spc_latin_genus, sidewalk]
  - [spc_latin_genus, user_type]
  - [spc_latin_genus, boro_ct]
  - [spc_latin_genus, spc_common_country]
  - [spc_latin_genus, created_at__year]
  - [spc_latin_genus, tree_dbh_01]
  # # spc_latin_genus, tree_dbh_01 + α のカラム名
  # - [spc_latin_genus, tree_dbh_01, created_at__year]
  # - [spc_latin_genus, tree_dbh_01, spc_common_country]
  # - [spc_latin_genus, tree_dbh_01, spc_latin_species]
  # - [spc_latin_genus, tree_dbh_01, curb_loc]
  # - [spc_latin_genus, tree_dbh_01, steward]
  # - [spc_latin_genus, tree_dbh_01, guards]
  # - [spc_latin_genus, tree_dbh_01, sidewalk]
  # - [spc_latin_genus, tree_dbh_01, user_type]
  # - [spc_latin_genus, tree_dbh_01, boro_ct]
  # 木の環境情報カラム
  - [curb_loc, steward, guards, sidewalk, user_type]
  - [curb_loc, guards, sidewalk]
  - [steward, user_type]
