input_cols_for_ordinal_encoder:
  - curb_loc
  - steward
  - guards
  - sidewalk
  - user_type
  - problems
  - spc_common
  - spc_latin
  - nta
  - nta_name
  - borocode
  - boro_ct
  - boroname
  - zip_city
  - cb_num
  - st_senate
  - st_assem
  - cncldist
  - tree_age_bins10
  - tree_dbh_01

group_keys_for_target_encoder:
  - ["tree_dbh_bins10"]
  - ["tree_age_bins10"]
  - ["tree_dbh_01"]
  - ["sidewalk"]
  - ["zip_city"]
  - ["curb_loc"]
  - ["steward"]
  - ["guards"]
  - ["user_type"]
  - ["nta"]
  - ["cb_num"]
  - ["boroname"]
  - ["st_senate"]
  - ["st_assem"]
  - ["cncldist"]
  - ["spc_common"]
  - ["problems"]
  - [tree_dbh_bins10, tree_age_bins10]
  - [tree_dbh_bins10, tree_dbh_01]
  - [tree_dbh_bins10, sidewalk]
  - [tree_dbh_bins10, zip_city]
  - [tree_dbh_bins10, curb_loc]
  - [tree_dbh_bins10, steward]
  - [tree_dbh_bins10, guards]
  - [tree_dbh_bins10, user_type]
  - [tree_dbh_bins10, nta]
  - [tree_dbh_bins10, cb_num]
  - [tree_dbh_bins10, boroname]
  - [tree_dbh_bins10, st_senate]
  - [tree_dbh_bins10, st_assem]
  - [tree_dbh_bins10, cncldist]
  - [tree_dbh_bins10, spc_common]
  - [tree_dbh_bins10, problems]
  - [tree_age_bins10, tree_dbh_01]
  - [tree_age_bins10, sidewalk]
  - [tree_age_bins10, zip_city]
  - [tree_age_bins10, curb_loc]
  - [tree_age_bins10, steward]
  - [tree_age_bins10, guards]
  - [tree_age_bins10, user_type]
  - [tree_age_bins10, nta]
  - [tree_age_bins10, cb_num]
  - [tree_age_bins10, boroname]
  - [tree_age_bins10, st_senate]
  - [tree_age_bins10, st_assem]
  - [tree_age_bins10, cncldist]
  - [tree_age_bins10, spc_common]
  - [tree_age_bins10, problems]
  - [tree_dbh_01, sidewalk]
  - [tree_dbh_01, zip_city]
  - [tree_dbh_01, curb_loc]
  - [tree_dbh_01, steward]
  - [tree_dbh_01, guards]
  - [tree_dbh_01, user_type]
  - [tree_dbh_01, nta]
  - [tree_dbh_01, cb_num]
  - [tree_dbh_01, boroname]
  - [tree_dbh_01, st_senate]
  - [tree_dbh_01, st_assem]
  - [tree_dbh_01, cncldist]
  - [tree_dbh_01, spc_common]
  - [tree_dbh_01, problems]
  - [sidewalk, zip_city]
  - [sidewalk, curb_loc]
  - [sidewalk, steward]
  - [sidewalk, guards]
  - [sidewalk, user_type]
  - [sidewalk, nta]
  - [sidewalk, cb_num]
  - [sidewalk, boroname]
  - [sidewalk, st_senate]
  - [sidewalk, st_assem]
  - [sidewalk, cncldist]
  - [sidewalk, spc_common]
  - [sidewalk, problems]
  - [zip_city, curb_loc]
  - [zip_city, steward]
  - [zip_city, guards]
  - [zip_city, user_type]
  - [zip_city, nta]
  - [zip_city, cb_num]
  - [zip_city, boroname]
  - [zip_city, st_senate]
  - [zip_city, st_assem]
  - [zip_city, cncldist]
  - [zip_city, spc_common]
  - [zip_city, problems]
  - [curb_loc, steward]
  - [curb_loc, guards]
  - [curb_loc, user_type]
  - [curb_loc, nta]
  - [curb_loc, cb_num]
  - [curb_loc, boroname]
  - [curb_loc, st_senate]
  - [curb_loc, st_assem]
  - [curb_loc, cncldist]
  - [curb_loc, spc_common]
  - [curb_loc, problems]
  - [steward, guards]
  - [steward, user_type]
  - [steward, nta]
  - [steward, cb_num]
  - [steward, boroname]
  - [steward, st_senate]
  - [steward, st_assem]
  - [steward, cncldist]
  - [steward, spc_common]
  - [steward, problems]
  - [guards, user_type]
  - [guards, nta]
  - [guards, cb_num]
  - [guards, boroname]
  - [guards, st_senate]
  - [guards, st_assem]
  - [guards, cncldist]
  - [guards, spc_common]
  - [guards, problems]
  - [user_type, nta]
  - [user_type, cb_num]
  - [user_type, boroname]
  - [user_type, st_senate]
  - [user_type, st_assem]
  - [user_type, cncldist]
  - [user_type, spc_common]
  - [user_type, problems]
  - [nta, cb_num]
  - [nta, boroname]
  - [nta, st_senate]
  - [nta, st_assem]
  - [nta, cncldist]
  - [nta, spc_common]
  - [nta, problems]
  - [cb_num, boroname]
  - [cb_num, st_senate]
  - [cb_num, st_assem]
  - [cb_num, cncldist]
  - [cb_num, spc_common]
  - [cb_num, problems]
  - [boroname, st_senate]
  - [boroname, st_assem]
  - [boroname, cncldist]
  - [boroname, spc_common]
  - [boroname, problems]
  - [st_senate, st_assem]
  - [st_senate, cncldist]
  - [st_senate, spc_common]
  - [st_senate, problems]
  - [st_assem, cncldist]
  - [st_assem, spc_common]
  - [st_assem, problems]
  - [cncldist, spc_common]
  - [cncldist, problems]
  - [spc_common, problems]

group_keys_for_target_encoder_r1:
  - ["tree_dbh_bins10"]
  - ["tree_age_bins10"]
  - ["tree_dbh_01"]
  - ["sidewalk"]
  - ["zip_city"]
  - ["curb_loc"]
  - ["steward"]
  - ["guards"]
  - ["user_type"]
  - ["nta"]
  - ["cb_num"]
  - ["boroname"]
  - ["st_senate"]
  - ["st_assem"]
  - ["cncldist"]
  - ["spc_common"]
  - ["problems"]
